// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jdOMwZfw0jzySnBVYltaCMJ7pf2nLUw',
    appId: '1:1080325854470:web:4100773edeb607de1b3a87',
    messagingSenderId: '1080325854470',
    projectId: 'raq-darjar',
    authDomain: 'raq-darjar.firebaseapp.com',
    storageBucket: 'raq-darjar.firebasestorage.app',
    measurementId: 'G-HM2S5CVWKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJ3ixarMi-ZRHjAlsqnFTTV4GLg4SQi0',
    appId: '1:1080325854470:android:e66c2d1094c011631b3a87',
    messagingSenderId: '1080325854470',
    projectId: 'raq-darjar',
    storageBucket: 'raq-darjar.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSgQFhSNgArs9ZbYtcl9Bxui2-Kb-Yf0',
    appId: '1:1080325854470:ios:3204b78a259842741b3a87',
    messagingSenderId: '1080325854470',
    projectId: 'raq-darjar',
    storageBucket: 'raq-darjar.firebasestorage.app',
    iosBundleId: 'ma.raqmain.darjar',
  );
}
